IR 1 implement incident class
katusiimeconrad/iReporter pull request #4
Opened 2021-09-09 12:34 UTC by benon123

i mplemented the incident class and also created respective enums so the person who is getting incidents carry on from here

2021-09-09 13:19 UTC, katusiimeconrad commented on src/org/pahappa/systems/models/Status.java
> +	under_investigation, rejected,resolved;
According to the Oracle Docs,https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html
 since enumerated items are constants, they should be UPPERCASED.

2021-09-09 13:36 UTC, benon123 commented on src/org/pahappa/systems/models/Status.java
> +	under_investigation, rejected,resolved;
i resolved it and pushed again

2021-09-09 13:37 UTC, katusiimeconrad approved these changes
Looks Good

2021-09-09 14:04 UTC, MutebiAlexKato requested changes
The contents of the enum should be uppercase. Also add "DRAFT" to the status enum.
the type of the incident should be an enum(in my opinion)

2021-09-09 14:48 UTC, katusiimeconrad commented on src/org/pahappa/systems/models/Incident.java
> +    private String type;
Type is an Enum of : type[Redflag, Intervention]

2021-09-09 14:51 UTC, katusiimeconrad commented on src/org/pahappa/systems/views/IReporter.java
> +		System.out.println("iReporter Benon");
Resolve the conflict

2021-09-10 05:47 UTC, benon123 commented on src/org/pahappa/systems/views/IReporter.java
> +		System.out.println("iReporter Benon");
i have resolved it

2021-09-10 05:55 UTC, idr3w reviewed
Looks okay

2021-09-10 06:01 UTC, Golder12 requested changes

2021-09-10 06:01 UTC, Golder12 commented on src/org/pahappa/systems/models/Status.java
> +	DRAFT,UNDER_INVESTIGATION, REJECTED,RESOLVED;
Draft shouldn't be a constant in this case since Status refers to what the admin is recording about incidents received through the system.

2021-09-10 06:13 UTC, Golder12 approved these changes

2021-09-10 06:14 UTC, benon123 commented
thanks for your reviews

2021-09-10 06:34 UTC, ttcollins requested changes

2021-09-10 06:34 UTC, ttcollins commented on src/org/pahappa/systems/models/Status.java
> +package org.pahappa.systems.models;
I suggest that all enums reside in one package, probably enum.

2021-09-10 06:47 UTC, MutebiAlexKato approved these changes

2021-09-10 07:04 UTC, ttcollins approved these changes
Well in @benon123

2021-09-10 07:05 UTC, ttcollins approved these changes

2021-09-10 07:08 UTC, fredmugerwa requested changes
We agreed on having a single commit for each pull request. Work with your team to have it fixed
<img width="1360" alt="Screen Shot 2021-09-10 at 9 49 37 AM" src="https://user-images.githubusercontent.com/83646778/132814186-f9e72f8a-3b8a-4c28-9642-847331b36758.png">

2021-09-10 07:12 UTC, fredmugerwa requested changes
You worked on 1 file but I see over 40 files changes. 
1. Delete these files(*.metdata) from your project
2. git rm --cached <file> all the files
3. Add the (.metadata)folder to the .gitignore file
4. git add .
5. git commit --amend
<img width="1421" alt="Screen Shot 2021-09-10 at 10 11 37 AM" src="https://user-images.githubusercontent.com/83646778/132814536-aa00936b-5185-43da-923c-25285dd44b79.png">

2021-09-10 07:21 UTC, fredmugerwa requested changes

2021-09-10 07:21 UTC, fredmugerwa commented on src/org/pahappa/systems/models/Incident.java
> +				+ ", toString()=" + super.toString() + "]";
The toString() method returns the String representation of the object. 
It wouldn't look nice if our Incident object is going to be represented by all this. I think you should use the title to represent the Incident object

2021-09-10 09:17 UTC, NakagweSharifah approved these changes

2021-09-10 09:33 UTC, reifred commented
> You worked on 1 file but I see over 40 files changes.
> 
> 1. Delete these files(*.metdata) from your project
> 2. git rm --cached  all the files
> 3. Add the (.metadata)folder to the .gitignore file
> 4. git add .
> 5. git commit --amend
> 
> <img alt="Screen Shot 2021-09-10 at 10 11 37 AM" width="1421" src="https://user-images.githubusercontent.com/83646778/132814536-aa00936b-5185-43da-923c-25285dd44b79.png">

@benon123 good progress, one issue remaining

2021-09-10 09:45 UTC, reifred approved these changes

2021-09-10 09:45 UTC, merged